name: api_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.6
  dart_jsonwebtoken: ^3.2.0
  google_generative_ai: ^0.4.0
  image: ^4.5.4
  mongo_dart: ^0.10.0
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4
  uuid: ^4.5.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
